import Head from 'next/head'
import Items from '../components/Items'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className='bg-white'>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Navbar />
      </Head>

      <main style={{minHeight:"90vh"}}>
        <Items />
      </main>

      <footer className='text-center bg-gray-800 py-5 text-sm leading-6 text-white-800'>
        Developed By Adi Murianto
      </footer>
    </div>
  )
}
